### PR TITLE
Fix pie rule used

### PR DESCRIPTION
**Pull request by faizsameerahmed96**

### CODE REVIEW

**Comment by miithi** [comment]
Hello, 
The step method processes the pie rule well but does not properly check for the case where the board might be empty. So, I think technically you could add an if statement representing an error instead if the board was empty.

**Comment by miithi** [comment]
self.is_pie_rule_usable = True is used twice (line 107), and for  "pie_rule_used": 1 if self.is_pie_rule_usable else 0, shouldn't that just be is_pie_rule_used instead? As it should be reflecting the status of is_pie_rule_used. Also, the red error in that line is because you're missing the comma at the end of the line.

**Comment by faizsameerahmed96** [comment]
Thanks @miithi, my understanding is that `is_pie_rule_usable` checks for that.

For eg: 
If `player_1` tries to use the pie rule (the only way it is possible to apply pie rule and the board is empty as per your comment), it checks the below code and throws an error.
```python
if self.agent_selection == "player_1":
                raise ValueError("Illegal move: Pie rule can only be used by Player 2.")
```

Is this what you were referring to or am I missing something here?

**Comment by ChristoferBerruz** [comment]
It looks good - we are setting the value back during reset. :shipit:

**Review by ChristoferBerruz — APPROVED** [review]

**Pull request merged**
